python run.py --do_train \
--data_dir ../Re-DocRED/data \
--transformer_type roberta \
--model_name_or_path roberta-large \
--display_name  ReDocRED/RoBERTa/teacher_trained \
--train_file train_revised.json \
--dev_file dev_revised.json \
--save_path ReDocRED/RoBERTa/teacher_trained \
--train_batch_size 4 \
--test_batch_size 8 \
--gradient_accumulation_steps 1 \
--num_labels 4 \
--lr_transformer 3e-5 \
--max_grad_norm 1.0 \
--evi_thresh 0.2 \
--warmup_ratio 0.06 \
--num_train_epochs 30.0 \
--seed 66 \
--num_class 97